*SYMBOLS
 IDENTIFICATION                   DIVISION.
 PROGRAM-ID.                      POPD110 .
 AUTHOR.                          SYSCOM COMPUTER ENGINEER CO.
 DATE-WRITTEN.                    80/05/28 - 10:15:15.
********************************************************************
*                                                                  *
*                    Code Generated Language                       *
*                    Tandem Request Program                        *
*     This Program is Generated by  SYSCOM A.P.G. Ver 1.00         *
*                                                                  *
********************************************************************
 ENVIRONMENT                      DIVISION.
 CONFIGURATION                    SECTION.
 SOURCE-COMPUTER.                 SYSCOM.
 OBJECT-COMPUTER.                 SYSCOM.
 SPECIAL-NAMES.
      CURSOR IS CRT-CURSOR,
      CRT STATUS IS CRT-STATUS,
      SCREEN CONTROL IS SCREEN-CONTROL.
*
 DATA                             DIVISION.
 WORKING-STORAGE                  SECTION.
      COPY "CMN/LIB/NEWVAR".
 01   MSG-CKRUNS.
      05  REPLY-C             PIC 9(04) COMP.
      05  FILLER              PIC X(22).
      05  COMM-LNK-C.
      COPY "CMN/LIB/COMMLNK".
 01  WS-G.
      05  WSDATE.
          10  WSYY                PIC 9(03).
          10  WSMM                PIC 9(02).
          10  WSDD                PIC 9(02).
      05  WSDATE-R REDEFINES WSDATE PIC 9(07).
      05  WSTIME.
          10  WS-HOUR             PIC 9(02).
          10  WS-MIN              PIC 9(02).
          10  WS-SEC              PIC 9(02).
          10  WS-CC               PIC 9(02).
      05  WSTIME-R.
          10  WS-HOUR-R           PIC 9(02).
          10  FILLER              PIC X(01) VALUE ":".
          10  WS-MIN-R            PIC 9(02).
          10  FILLER              PIC X(01) VALUE ":".
          10  WS-SEC-R            PIC 9(02).
      05  X01                     PIC 9(04) COMP.
      05  W-TOP                   PIC 9(02) VALUE 01.
      05  W-BOTTOM                PIC 9(03) VALUE 007.
*
 01   MSG-FILE-R.
      05  WR-ADVISORY             PIC X(78).
      COPY "CMN/LIB/MSG".
      02  MSG-BUF.
          05  MSG-CA1.
              10  CA03                           PIC  9(008)       COMP.
          05  MSG-CA2.
              10  CA01                           PIC  X(020)           .
              10  CA02                           PIC  X(012)           .
              10  CA04                           PIC  X(010)           .
              10  CA05                           PIC  X(002)           .
              10  CA06                           PIC  X(020)           .
              10  CA07                           PIC  X(020)           .
      02  COMM-LNK.
      COPY "CMN/LIB/COMMLNK".
*
      02  WCHK-G.
          10  WCHK-01         PIC X OCCURS   7 TIMES.
      02  WCHK-G0     REDEFINES   WCHK-G.
          10  WCHK-001        PIC X                    .
          10  WCHK-002        PIC X                    .
          10  WCHK-003        PIC X                    .
          10  WCHK-004        PIC X                    .
          10  WCHK-005        PIC X                    .
          10  WCHK-006        PIC X                    .
          10  WCHK-007        PIC X                    .
 LINKAGE  SECTION.
 01   COMM-LNK1.
      COPY "CMN/LIB/COMMLNK".
 SCREEN                                SECTION.
 01   SCRN99  ERASE EOS.
      05  SCRN-FORM.
          10  FILLER  LINE 01, COL 02      VALUE
          "POPD110".
          10  FILLER  LINE 02, COL 22      VALUE
          "付  款  方  式  建  立  作  業".
          10  FILLER  LINE 03, COL 01      VALUE
          "────────────────────────────".
          10  FILLER  LINE 03, COL 57      VALUE
          "────────── --".
          10  FILLER  LINE 06, COL 18      VALUE
          "付  款  方  式  代  號 :".
          10  FILLER  LINE 09, COL 18      VALUE
          "付 款 方 式 說 明 (中) :".
          10  FILLER  LINE 12, COL 18      VALUE
          "付 款 方 式 說 明 (英) :".
      05  SCRN-DATA.
          10  CA01-CMP-NAME-L                LINE 01, COL 27
          PIC X(020)               FROM   CA01.
          10  CA01-TERM-ID-L                 LINE 01, COL 66
          PIC X(012)               FROM   CA02.
          10  CA02-TODAY                     LINE 02, COL 02
          PIC 999/99/99             FROM   CA03.
          10  CA02-USER-NAME-L               LINE 02, COL 66
          PIC X(010)               FROM   CA04.
          10  CA06-POPMPAY-01                LINE 06, COL 44
          PIC X(002)               USING  CA05
                                              UNDERLINE AUTO
                                 .
          10  CA09-POPMPAY-02                LINE 09, COL 44
          PIC X(020)               USING  CA06
                                              UNDERLINE AUTO
                                 .
          10  CA12-POPMPAY-03                LINE 12, COL 44
          PIC X(020)               USING  CA07
                                              UNDERLINE AUTO
                                 .
      05  FILLER  LINE 23, COL 02      VALUE
          "    <F1>查當筆,<F3>查次筆,<F5>清除,<F6>增加,<F7>修".
      05  FILLER  LINE 23, COL 52      VALUE
          "改,<F9>刪除,<F10>結束"                            .
      05  D99     LINE 24, COL 02  PIC X(72)   FROM    ERR-BUF
                                 .
*
 PROCEDURE        DIVISION        USING   COMM-LNK1.
*
*DECLARATIVES.
*SCREEN-RECOVERY             SECTION.
*    USE FOR SCREEN RECOVERY.
*END DECLARATIVES.
 MAIN SECTION.
*
 0000-MAIN.
      PERFORM 0100-INIT.
      PERFORM 1000-PROC    UNTIL CMD-KEY.
 0099-MAIN.
      CANCEL ALL.
      EXIT PROGRAM.
 0100-INIT.
      MOVE SYS-DATE-L OF COMM-LNK1 TO WSDATE-R.
      ACCEPT      WSTIME  FROM    TIME
      MOVE        WS-HOUR TO      WS-HOUR-R
      MOVE        WS-MIN  TO      WS-MIN-R
      MOVE        WS-SEC  TO      WS-SEC-R.
      MOVE        COMM-LNK1       TO      COMM-LNK
*     MOVE        SPACES  TO      ERR-BUF
      DISPLAY SPACES LINE 1 COL 1 ERASE SCREEN.
       DISPLAY SCRN99.
      PERFORM 9998-CKRUN.
      PERFORM 2400-PROC
      MOVE    99          TO      EVENT.
* F1->INQUARY, F5->CLEAR, F6 -> ADD, F7 -> UPDATE, F9->DELETE
* FOR GH/SA
* F1->INQUARY, F5->CLEAR, F16 -> ADD, F10 -> UPDATE, SF12->DELETE
* PROCESS SECTION
*
 1000-PROC.
      MOVE    99      TO      EVENT
      MOVE    SPACES  TO      ERR-BUF
      PERFORM 6000-GET    UNTIL   MAINTAIN-KEY
      MOVE    "處理中   !"   TO  ERR-BUF
      DISPLAY    D99     OF      SCRN99
      MOVE    SPACES      TO      WCHK-G
      IF  CLR-KEY
          PERFORM  2400-PROC
      ELSE
      IF  NOT CMD-KEY
          MOVE     W-TOP     TO     X01
          PERFORM  4000-CHK  UNTIL  X01 > W-BOTTOM OR EOF-KEY
          IF  WCHK-G  =       SPACES
              PERFORM 1010-PROC
          ELSE
              PERFORM 6520-CRT
              PERFORM 6500-CRT.
 1010-PROC.
          PERFORM   8300-WRITE-MSG.
      PERFORM   6500-CRT.
* CLEAR ITEM
 2400-PROC.
      MOVE    LOW-VALUE
          TO  MSG-CA1
      MOVE    SPACES
          TO  MSG-CA2
      MOVE     CMP-NAME-L OF COMM-LNK1
          TO  CA01                               .
      MOVE     TERM-ID-L OF COMM-LNK1
          TO  CA02                               .
      MOVE    WSDATE-R
          TO  CA03                               .
      MOVE     USER-NAME-L OF COMM-LNK1
          TO  CA04                               .
      MOVE    SPACES  TO      ERR-BUF
      PERFORM     6500-CRT.
*
* CHECK SECTION
*
 4000-CHK.
          ADD     007             TO  X01
      IF  X01 <   W-TOP
          MOVE    W-BOTTOM        TO      X01.
      ADD     1               TO      X01.
*
 5100-ERR.
      MOVE    "ＴＭＦ錯誤"   TO  ERR-BUF.
*
* SCREEN I/O SECTION
*
 6000-GET.
      ACCEPT SCRN99 ON EXCEPTION PERFORM 6010-PROC.
      IF  EXIT-KEY
          MOVE "Y" TO EXIT-L OF COMM-LNK.
 6010-PROC.
      EVALUATE CRT-STATUS
          WHEN 01
             MOVE 01 TO EVENT
          WHEN 02
             MOVE 02 TO EVENT
          WHEN 03
             MOVE 03 TO EVENT
          WHEN 04
             MOVE 04 TO EVENT
          WHEN 05
             MOVE 05 TO EVENT
          WHEN 06
             MOVE 06 TO EVENT
          WHEN 07
             MOVE 07 TO EVENT
          WHEN 08
             MOVE 08 TO EVENT
          WHEN 09
             MOVE 09 TO EVENT
          WHEN 10
             MOVE 10 TO EVENT
          WHEN 11
             MOVE 17 TO EVENT
          WHEN 12
             MOVE 18 TO EVENT
          WHEN 13
             MOVE 19 TO EVENT
          WHEN 14
             MOVE 20 TO EVENT
          WHEN 15
             MOVE 21 TO EVENT
          WHEN 16
             MOVE 22 TO EVENT
          WHEN 17
             MOVE 23 TO EVENT
          WHEN 18
             MOVE 24 TO EVENT
          WHEN 19
             MOVE 25 TO EVENT
          WHEN 20
             MOVE 26 TO EVENT
          WHEN 67
             MOVE 33 TO EVENT
          WHEN 68
             MOVE 34 TO EVENT
          WHEN 10
             MOVE 35 TO EVENT
          WHEN OTHER
             MOVE 99 TO EVENT
      END-EVALUATE.
 6500-CRT.
      DISPLAY
              SCRN99.
 6520-CRT.
      IF WCHK-G NOT = SPACES
         PERFORM VARYING X01 FROM W-TOP BY 1 UNTIL
                X01 > W-BOTTOM
            IF WCHK-01(X01) = "!"
               SET GOTO-FIELD TO TRUE
               EVALUATE X01
                  WHEN 005
                       MOVE 001 TO CONTROL-VALUE
               END-EVALUATE
               ADD 1 W-BOTTOM GIVING X01
            END-IF
         END-PERFORM
      END-IF.
 8300-WRITE-MSG.
      MOVE      COMM-LNK     TO COMM-LNK1.
      CALL "POPD110S" USING MSG-G ON EXCEPTION PERFORM 9099-EXP.
      EVALUATE REPLY-CODE
        WHEN  0
              PERFORM 9001-EXP
        WHEN  997
              PERFORM 9002-EXP
        WHEN  998
              PERFORM 9003-EXP
        WHEN  999
              PERFORM 9004-EXP
      END-EVALUATE.
*********  ADD FOR MIS2 {
*         UNDER PATHWAY "$MIS"
*         CONTINUE
*********  } ADD FOR MIS2
*             REPLY   CODE    0           YIELDS  MSG-G
*                     CODE    997, 998    YIELDS  REPLY-01 ERR-BUF
*                     CODE    999         YIELDS  REPLY-01
*                                                 MSG-FILE-R
*             ON  ERROR   PERFORM 9099-EXP.
*     PERFORM     ONE OF  9001-EXP        9002-EXP
*                         9003-EXP        9004-EXP
 9001-EXP.
      MOVE        "處理正確 !"    TO      ERR-BUF.
 9002-EXP.
 9003-EXP.
 9004-EXP.
      IF  NOT ( INQ-KEY OR READ-KEY )
          CONTINUE.
 9099-EXP.
      COPY "CMN/LIB/CALLERR".
      COPY "CMN/LIB/CKRUN".
