*SYMBOLS;INSPECT;SAVE ALL;SEARCH SUBRTN
 IDENTIFICATION                   DIVISION.
 PROGRAM-ID.                      POPD110S.
 AUTHOR.                          SYSCOM COMPUTER ENGINEER CO.
 DATE-WRITTEN.                    80/05/28 - 10:15:30.
********************************************************************
*                                                                  *
*                 Dataentry Generated Language                     *
*                    Tandem Server  Program                        *
*     This Program is Generated by  SYSCOM A.P.G. Ver 1.00         *
*                                                                  *
********************************************************************
 ENVIRONMENT                      DIVISION.
 CONFIGURATION                    SECTION.
 SOURCE-COMPUTER.                 SYSCOM.
 OBJECT-COMPUTER.                 SYSCOM.
 INPUT-OUTPUT                     SECTION.
 FILE-CONTROL.
*
       COPY "POP/LIB/POPMPAY.SL".
*
*
*
*
 DATA                             DIVISION.
 FILE                             SECTION.
*
       COPY "POP/LIB/POPMPAY.FD".
*
 WORKING-STORAGE                  SECTION.
      COPY "CMN/LIB/NEWVAR".
 01   PID                         PIC X(08) VALUE "POPD110S".
 01   STAT-POPMPAY                PIC X(02).
      88  VALID-POPMPAY           VALUE "00", "96", "97".
      88  END-POPMPAY             VALUE "10", "23".
 01   STAT-ERRLOG                 PIC X(02).
      88  VALID-ERRLOG            VALUE "00", "96", "97".
      88  END-ERRLOG              VALUE "10", "23".
 01   STAT-MSG                    PIC X(02).
      88  VALID-MSG               VALUE "00", "96", "97".
      88  END-MSG                 VALUE "10", "23".
 01   WS-G.
      05  W-TOP                   PIC 9(02) VALUE 01.
      05  W-BOTTOM                PIC 9(03) VALUE 007.
      05  WSDATE.
          10  WSYY                PIC 9(03).
          10  WSMM                PIC 9(02).
          10  WSDD                PIC 9(02).
      05  WSDATE-R REDEFINES WSDATE PIC 9(07).
      05  WSTIME.
          10  WS-HOUR             PIC 9(02).
          10  WS-MIN              PIC 9(02).
          10  WS-SEC              PIC 9(02).
          10  WS-CC               PIC 9(02).
      05  WSTIME-R.
          10  WS-HOUR-R           PIC 9(02).
          10  FILLER              PIC X(01) VALUE ":".
          10  WS-MIN-R            PIC 9(02).
          10  FILLER              PIC X(01) VALUE ":".
          10  WS-SEC-R            PIC 9(02).
 01   ENTRY-G.
      05  START-FIELD.
          10  START-NO            PIC 9(10).
          10  FILLER              PIC X(10).
      05  END-FIELD.
          10  END-NO              PIC 9(10).
          10  FILLER              PIC X(10).
      05  FORM-DATE               PIC 9(07).
      05  FORM-DATE-R             REDEFINES FORM-DATE.
          10  FORM-YY             PIC 9(03).
          10  FORM-MM             PIC 9(02).
          10  FORM-DD             PIC 9(02).
      05  FORM-PRINTER            PIC X(02) VALUE "01".
* COMM AREA
* FUNCTION KEY TABLE & INDEX TABLE.
* Param of SETMODE
 01   FILE-NO                     PIC S9(04) COMP VALUE 0.
 01   FILE-NAME                   PIC X(24).
 01   ERR-CODE                    PIC S9(04) COMP VALUE 0.
 01   FUNC-CODE                   PIC S9(04) COMP VALUE 4.
 01   PARAM-CODE1                 PIC S9(04) COMP VALUE 3.
 01   PARAM-CODE2                 PIC S9(04) COMP VALUE 0.
*
 01   MSG-DG.
      05  M88                     PIC X(10) VALUE "起始錯誤 !".
      05  M89                     PIC X(10) VALUE "讀檔錯誤 !".
      05  M90                     PIC X(10) VALUE "開檔錯誤 !".
      05  M91                     PIC X(10) VALUE "讀檔結束 !".
      05  M92                     PIC X(10) VALUE "寫入錯誤 !".
      05  M93                     PIC X(10) VALUE "更改錯誤 !".
      05  M94                     PIC X(10) VALUE "刪除錯誤 !".
      05  M95                     PIC X(10) VALUE "處理中   !".
      05  M96                     PIC X(10) VALUE "處理完畢 !".
      05  M97                     PIC X(10) VALUE "確定(Y/N)?".
      05  M98                     PIC X(10) VALUE "輸入錯誤 !".
      05  M99                     PIC X(10) VALUE "處理正確 !".
*
 01   STU.
      05  STAT                    PIC 99.
          88  STAT-OK             VALUE   00 THRU 09.
          88  STAT-EOF            VALUE   10.
      05  STAT-R REDEFINES STAT   PIC 99.
  01  INDEX-G.
     05 X01                       PIC 9(4)  COMP.
     05 X02                       PIC 9(4)  COMP.
     05 X03                       PIC 9(4)  COMP.
     05 Y01                       PIC 9(4)  COMP.
     05 Y02                       PIC 9(4)  COMP.
     05 Y03                       PIC 9(4)  COMP.
     05 DUMMY                     PIC X.
*    05 ERR-FILE                  PIC X(08).
     05 H000A                     PIC 9(4)  COMP   VALUE 10.
     05 H000A-R  REDEFINES H000A.
        10 FILLER                 PIC X.
        10 H00A                   PIC X.
      05  LF-BUF.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
*    X98: PAGE CNT         X99: LINE CNT
 01  PRINTER-G.
     05 X97                       PIC 9(5) COMP VALUE 0.
     05 X98                       PIC 9(5) COMP VALUE 1.
     05 X99                       PIC 9(2) COMP VALUE 0.
 01  FLAG-G.
     05 F01                       PIC X  VALUE SPACES.
        88 F01-ON                 VALUE  "Y".
        88 F01-OFF                VALUE  "N".
     05 F02                       PIC X  VALUE SPACES.
        88 F02-ON                 VALUE  "Y".
        88 F02-OFF                VALUE  "N".
     05 F03                       PIC X  VALUE SPACES.
        88 F03-ON                 VALUE  "Y".
        88 F03-OFF                VALUE  "N".
     05 FLAG-FILE                 PIC X  VALUE SPACES.
        88  FILE-OFF              VALUE  "N", "n".
 01  FUNC-KEY-GROUP.
     05 CODE-CMD-KEY              PIC   99  COMP     VALUE 10.
     05 CODE-EOF-KEY              PIC   99  COMP     VALUE 99.
*
 01   MSG-FILE-R.
      05  REPLY-CODE-1            PIC 9(04) COMP.
      05  FILLER                  PIC X(02).
      05  WR-ADVISORY             PIC X(78).
      05  WCHK-G-R                PIC X(007).
 LINKAGE SECTION.
      COPY "CMN/LIB/MSG".
      02  MSG-BUF.
          05  MSG-CA1.
              10  CA03                           PIC  9(008)       COMP.
          05  MSG-CA2.
              10  CA01                           PIC  X(020)           .
              10  CA02                           PIC  X(012)           .
              10  CA04                           PIC  X(010)           .
              10  CA05                           PIC  X(002)           .
              10  CA06                           PIC  X(020)           .
              10  CA07                           PIC  X(020)           .
      02  COMM-LNK.
      COPY "CMN/LIB/COMMLNK".
*
      02  WCHK-G.
          10  WCHK-01         PIC X OCCURS   7 TIMES.
      02  WCHK-G0     REDEFINES   WCHK-G.
          10  WCHK-001        PIC X                    .
          10  WCHK-002        PIC X                    .
          10  WCHK-003        PIC X                    .
          10  WCHK-004        PIC X                    .
          10  WCHK-005        PIC X                    .
          10  WCHK-006        PIC X                    .
          10  WCHK-007        PIC X                    .
 PROCEDURE                        DIVISION USING MSG-G.
*
      COPY "CMN/LIB/DECL".
 MAIN SECTION.
*
 0000-MAIN.
      PERFORM 0100-INIT
      PERFORM 1000-PROC
      PERFORM 8600-CLOSE-ALL.
 0099-EXIT.
      CANCEL ALL.
      EXIT PROGRAM.
 0100-INIT.
      MOVE SYS-DATE-L TO WSDATE-R.
      ACCEPT      WSTIME  FROM    TIME
      MOVE        WS-HOUR TO      WS-HOUR-R
      MOVE        WS-MIN  TO      WS-MIN-R
      MOVE        WS-SEC  TO      WS-SEC-R.
      MOVE        "00"    TO      STAT
      PERFORM 0110-INIT.
      IF  NOT STAT-OK
          PERFORM 6500-CRT
          GO TO   0099-EXIT.
 0110-INIT.


      INITIALIZE  POPMPAY-R .
      IF  STAT-POPMPAY  NOT = "83"
      IF  STAT-OK
          PERFORM         8000-OPENS-POPMPAY .
      IF  NOT STAT-OK
          PERFORM 5090-ERR.
 0150-INIT.
      MOVE    "00"        TO      STAT.
      IF  NOT STAT-OK
          PERFORM 5090-ERR.
* F1->INQUARY, F5->CLEAR, F6 -> ADD, F7 -> UPDATE, F9->DELETE
* PROCESS SECTION
*
 1000-PROC.
      START TRANSACTION.
      PERFORM 6000-GET
      IF  NOT CMD-KEY
          PERFORM 3000-MOVE
          PERFORM 0150-INIT.
      IF  INQ-KEY  OR   READ-KEY
          PERFORM  2500-PROC
      ELSE
      IF  ADD-KEY   OR  UPD-KEY OR      DEL-KEY
          PERFORM  1010-PROC.
      IF  NOT CMD-KEY
          PERFORM 6500-CRT.
 1010-PROC.
      MOVE  "00"       TO   STAT.
      IF  NOT FILE-OFF    AND
          ( UPD-KEY OR    DEL-KEY )
          PERFORM 3000-MOVE
          PERFORM 8200-READL-POPMPAY .
      IF  NOT STAT-OK
          IF  UPD-KEY
              PERFORM  5093-ERR
          ELSE
          IF  DEL-KEY
              PERFORM  5094-ERR
          ELSE
              PERFORM  5089-ERR
      ELSE
          MOVE     SPACES    TO     WCHK-G
          MOVE     W-TOP     TO     X01
          PERFORM  3000-MOVE
          PERFORM  4000-CHK  UNTIL  X01 > W-BOTTOM OR EOF-KEY
          PERFORM  6520-CRT
          IF  ADD-KEY   OR  UPD-KEY OR  DEL-KEY
              PERFORM 3710-PROC
              IF  ADD-KEY
                  PERFORM  2100-PROC
              ELSE
              IF  UPD-KEY
                  PERFORM  2200-PROC
              ELSE
              IF  DEL-KEY
                  PERFORM  2300-PROC.
* ADD
 2100-PROC.
      IF  NOT FILE-OFF
          PERFORM 8300-WRITE-POPMPAY .
      IF  NOT STAT-OK   AND NOT FILE-OFF
          PERFORM    5092-ERR.
* UPDATE
 2200-PROC.
      IF  NOT FILE-OFF
          PERFORM 8300-REWRITE-POPMPAY .
      IF  NOT STAT-OK   AND NOT FILE-OFF
          PERFORM    5093-ERR.
* DELETE
 2300-PROC.
      IF  NOT FILE-OFF
          PERFORM 8400-DELETE-POPMPAY .
      IF  NOT STAT-OK   AND NOT FILE-OFF
          PERFORM     5094-ERR.
* INQUARY
 2500-PROC.
          PERFORM 3000-MOVE
      IF  NOT FILE-OFF
      IF  READ-KEY
          PERFORM 8200-READN-POPMPAY
      ELSE
          PERFORM 8101-POPMPAY-PK-POPMPAY
      IF  STAT-OK
          PERFORM 8200-READS-POPMPAY
      ELSE
      IF  INQ-KEY
          MOVE    "10"            TO      STAT.
      IF  STAT-OK
          MOVE     SPACES    TO     WCHK-G
          MOVE     W-TOP     TO     X01
          PERFORM  4000-CHK  UNTIL  X01 > W-BOTTOM OR EOF-KEY
          PERFORM 3710-PROC
      ELSE
      IF  STAT-EOF
          PERFORM     5091-ERR
      ELSE
          PERFORM     5089-ERR.
      MOVE W-TOP  TO X01.
*
* MOVEMENT SECTION
*
* PUSH ITEM
 3000-MOVE.
      MOVE    CA05
          TO  POPMPAY-01                         .
      MOVE    CA06
          TO  POPMPAY-02                         .
      MOVE    CA07
          TO  POPMPAY-03                         .
* POP  ITEM
 3010-MOVE.
      MOVE    CMP-NAME-L
          TO  CA01                               .
      MOVE    TERM-ID-L
          TO  CA02                               .
      MOVE    USER-NAME-L
          TO  CA04                               .
      MOVE    POPMPAY-01
          TO  CA05                               .
      MOVE    POPMPAY-02
          TO  CA06                               .
      MOVE    POPMPAY-03
          TO  CA07                               .
 3710-PROC.
*
* CHECK SECTION
*
 4000-CHK.
      IF  X01 =   005
          PERFORM 4105-CHK
      ELSE
      IF  X01 <   W-TOP
          MOVE    W-BOTTOM        TO      X01.
      ADD     1               TO      X01.
 4105-CHK.
      IF  NOT ( POPMPAY-01 NOT = SPACES)
          MOVE    "!"     TO      WCHK-01(005).
 4910-CHK.
*
* ERROR SECTION
*
      COPY "CMN/LIB/ERRPROC".
 6000-GET.
      MOVE    0               TO      REPLY-CODE.
 6500-CRT.
      IF  REPLY-CODE = 0
          PERFORM 3010-MOVE
          COMMIT TRANSACTION
      ELSE
          ROLLBACK TRANSACTION.
 6520-CRT.
      IF  WCHK-G  NOT =   SPACES
          PERFORM 6522-CRT
          MOVE    CODE-EOF-KEY    TO      EVENT
          MOVE    WCHK-G   TO   WCHK-G-R
          PERFORM 5098-ERR.
 6522-CRT.
      MOVE    "輸入錯誤 !"    TO  ERR-MSG0.
      IF  WCHK-01(005)    NOT =   SPACES
         MOVE "付款方式代號不得為空白"
                                  TO      ERR-MSG1               .
*
* FILE I/O SECTION
*
 8000-OPENS-POPMPAY .
      OPEN    I-O     POPMPAY       .
      MOVE    STAT    TO      STAT-POPMPAY .
      IF  NOT STAT-OK
          MOVE        "POPMPAY "          TO  ERR-FILE.
 8100-POPMPAY-PK-POPMPAY.
      START POPMPAY  KEY IS NOT < POPMPAY-PK
                  .
      MOVE    STAT    TO      STAT-POPMPAY .
      IF  NOT STAT-OK
          MOVE        "POPMPAY "          TO  ERR-FILE.
 8101-POPMPAY-PK-POPMPAY.
      START   POPMPAY  KEY IS >    POPMPAY-PK
                  .
      MOVE    STAT    TO      STAT-POPMPAY .
      IF  NOT STAT-OK
          MOVE        "POPMPAY "          TO  ERR-FILE.
 8200-READS-POPMPAY.
      READ POPMPAY  NEXT
                  .
      MOVE    STAT    TO      STAT-POPMPAY .
      IF  NOT STAT-OK
          MOVE        "POPMPAY "          TO  ERR-FILE.
 8200-READN-POPMPAY.
      READ POPMPAY
                  .
      MOVE    STAT    TO      STAT-POPMPAY .
      IF  NOT STAT-OK
          MOVE        "POPMPAY "          TO  ERR-FILE.
 8200-READL-POPMPAY.
      READ POPMPAY  WITH LOCK
                  .
      MOVE    STAT    TO      STAT-POPMPAY .
      IF  NOT STAT-OK
          MOVE        "POPMPAY "          TO  ERR-FILE.
 8300-WRITE-POPMPAY .
        WRITE POPMPAY-R             .
      MOVE    STAT    TO      STAT-POPMPAY .
      IF  NOT STAT-OK
          MOVE        "POPMPAY "          TO  ERR-FILE.
 8300-REWRITE-POPMPAY .
      REWRITE POPMPAY-R      .
      MOVE    STAT    TO      STAT-POPMPAY .
      IF  NOT STAT-OK
          MOVE        "POPMPAY "          TO  ERR-FILE.
 8400-DELETE-POPMPAY .
      DELETE  POPMPAY   .
      MOVE    STAT    TO      STAT-POPMPAY .
      IF  NOT STAT-OK
          MOVE        "POPMPAY "          TO  ERR-FILE.
 8600-CLOSE-ALL.
      CLOSE                        POPMPAY .
