*SYMBOLS;INSPECT;SAVE ALL
 IDENTIFICATION                   DIVISION.
 PROGRAM-ID.                      POPD100S.
 AUTHOR.                          SYSCOM COMPUTER ENGINEER CO.
 DATE-WRITTEN.                    81/01/16 - 11:57:02.
********************************************************************
*                                                                  *
*                 Dataentry Generated Language                     *
*                    Tandem Server  Program                        *
*     This Program is Generated by  SYSCOM A.P.G. Ver 1.00         *
*                                                                  *
*20191030 BY RICK 加強對銀行帳號檢核                               * 
********************************************************************
 ENVIRONMENT                      DIVISION.
 CONFIGURATION                    SECTION.
 SOURCE-COMPUTER.                 SYSCOM.
 OBJECT-COMPUTER.                 SYSCOM.
 INPUT-OUTPUT                     SECTION.
 FILE-CONTROL.
*
       COPY "ORD/LIB/ORDVEND.SL".
       COPY "POP/LIB/POPMVDR.SL".
       COPY "POP/LIB/POPMVDN.SL".
       COPY "POP/LIB/POPMMEN.SL".
       COPY "POP/LIB/POPMCMP.SL".
       COPY "POP/LIB/POPMCAR.SL".
       COPY "POP/LIB/POPMLOC.SL".
       COPY "POP/LIB/POPMPAY.SL".
       COPY "POP/LIB/POPMPRI.SL".
       COPY "INC/LIB/INCMBNK.SL".
**    COPY     IMSMSRT                      OF "OAIMSG.SELLIB".
*
 DATA                             DIVISION.
 FILE                             SECTION.
*
       COPY "ORD/LIB/ORDVEND.FD".
       COPY "POP/LIB/POPMVDR.FD".
       COPY "POP/LIB/POPMVDN.FD".
       COPY "POP/LIB/POPMMEN.FD".
       COPY "POP/LIB/POPMCMP.FD".
       COPY "POP/LIB/POPMCAR.FD".
       COPY "POP/LIB/POPMLOC.FD".
       COPY "POP/LIB/POPMPAY.FD".
       COPY "POP/LIB/POPMPRI.FD".
       COPY "INC/LIB/INCMBNK.FD".
*FD   IMSMSRT         LABEL   RECORD  OMITTED .
*     COPY     IMSMSRT                      OF "OAIMSG.FDNLIB".
*
 WORKING-STORAGE                  SECTION.
      COPY "CMN/LIB/NEWVAR".
 01   PID                         PIC X(08) VALUE "POPD100S".
 01   STAT-ORDVEND                PIC X(02).
      88  VALID-ORDVEND           VALUE "00", "96", "97".
      88  END-ORDVEND             VALUE "10", "23".
 01   STAT-POPMVDR                PIC X(02).
      88  VALID-POPMVDR           VALUE "00", "96", "97".
      88  END-POPMVDR             VALUE "10", "23".
 01   STAT-POPMVDN                PIC X(02).
      88  VALID-POPMVDN           VALUE "00", "96", "97".
      88  END-POPMVDN             VALUE "10", "23".
 01   STAT-POPMMEN                PIC X(02).
      88  VALID-POPMMEN           VALUE "00", "96", "97".
      88  END-POPMMEN             VALUE "10", "23".
 01   STAT-POPMCMP                PIC X(02).
      88  VALID-POPMCMP           VALUE "00", "96", "97".
      88  END-POPMCMP             VALUE "10", "23".
 01   STAT-POPMCAR                PIC X(02).
      88  VALID-POPMCAR           VALUE "00", "96", "97".
      88  END-POPMCAR             VALUE "10", "23".
 01   STAT-POPMLOC                PIC X(02).
      88  VALID-POPMLOC           VALUE "00", "96", "97".
      88  END-POPMLOC             VALUE "10", "23".
 01   STAT-POPMPAY                PIC X(02).
      88  VALID-POPMPAY           VALUE "00", "96", "97".
      88  END-POPMPAY             VALUE "10", "23".
 01   STAT-POPMPRI                PIC X(02).
      88  VALID-POPMPRI           VALUE "00", "96", "97".
      88  END-POPMPRI             VALUE "10", "23".
 01   STAT-INCMBNK                PIC X(02).
      88  VALID-INCMBNK           VALUE "00", "96", "97".
      88  END-INCMBNK             VALUE "10", "23".
*01   STAT-IMSMSRT                PIC X(02).
*     88  VALID-IMSMSRT           VALUE "00", "96", "97".
*     88  END-IMSMSRT             VALUE "10", "23".
 01   STAT-ERRLOG                 PIC X(02).
      88  VALID-ERRLOG            VALUE "00", "96", "97".
      88  END-ERRLOG              VALUE "10", "23".
 01   STAT-MSG                    PIC X(02).
      88  VALID-MSG               VALUE "00", "96", "97".
      88  END-MSG                 VALUE "10", "23".
 01   WS-G.
      05  W-TOP                   PIC 9(02) VALUE 01.
      05  W-BOTTOM                PIC 9(03) VALUE 051.
      05  WSDATE.
          10  WSYY                PIC 9(03).
          10  WSMM                PIC 9(02).
          10  WSDD                PIC 9(02).
      05  WSDATE-R REDEFINES WSDATE PIC 9(07).
      05  WSTIME.
          10  WS-HOUR             PIC 9(02).
          10  WS-MIN              PIC 9(02).
          10  WS-SEC              PIC 9(02).
          10  WS-CC               PIC 9(02).
      05  WSTIME-R.
          10  WS-HOUR-R           PIC 9(02).
          10  FILLER              PIC X(01) VALUE ":".
          10  WS-MIN-R            PIC 9(02).
          10  FILLER              PIC X(01) VALUE ":".
          10  WS-SEC-R            PIC 9(02).
 01   ENTRY-G.
      05  START-FIELD.
          10  START-NO            PIC 9(10).
          10  FILLER              PIC X(10).
      05  END-FIELD.
          10  END-NO              PIC 9(10).
          10  FILLER              PIC X(10).
      05  FORM-DATE               PIC 9(07).
      05  FORM-DATE-R             REDEFINES FORM-DATE.
          10  FORM-YY             PIC 9(03).
          10  FORM-MM             PIC 9(02).
          10  FORM-DD             PIC 9(02).
      05  FORM-PRINTER            PIC X(02) VALUE "01".
*      COPY "CHK/LIB/CHKDATE.FD".
       COPY "CMN/LIB/CHKDATE.CPY".
 01 WORK-AREAS. 
    05 VALID-FLAG     PIC X.
    05 WK-TYPE        PIC X.
    05 WK-POPMVDR-01             PIC X(04).
    05 WK-ERR-MSG0               PIC X(10).
    05 WK-POPMVDR-DELETE         PIC X(01).
    05 WK-POPMVDR-12             PIC X(10).
*B加強對銀行帳號檢核  20191030 BY RICK ----------------  *     
    05 WK-POPMVDR-33.
       10  WK-POPMVDR-33-01      PIC X(01) OCCURS  20 TIMES.
    05 FLAG-SW.
       10 FLAG-SW-01                PIC 9(01) VALUE 0.
         88  FLAG-SW-01-NUMERIC               VALUE 0.
         88  FLAG-SW-01-NONNUM                VALUE 1.
         88  FLAG-SW-01-ERR                   VALUE 2.
*E加強對銀行帳號檢核  20191030 BY RICK ----------------  *     
* COMM AREA
* FUNCTION KEY TABLE & INDEX TABLE.
* Param of SETMODE
 01   FILE-NO                     PIC S9(04) COMP VALUE 0.
 01   FILE-NAME                   PIC X(24).
 01   ERR-CODE                    PIC S9(04) COMP VALUE 0.
 01   FUNC-CODE                   PIC S9(04) COMP VALUE 4.
 01   PARAM-CODE1                 PIC S9(04) COMP VALUE 3.
 01   PARAM-CODE2                 PIC S9(04) COMP VALUE 0.
*
 01   MSG-DG.
      05  M88                     PIC X(10) VALUE "起始錯誤 !".
      05  M89                     PIC X(10) VALUE "讀檔錯誤 !".
      05  M90                     PIC X(10) VALUE "開檔錯誤 !".
      05  M91                     PIC X(10) VALUE "讀檔結束 !".
      05  M92                     PIC X(10) VALUE "寫入錯誤 !".
      05  M93                     PIC X(10) VALUE "更改錯誤 !".
      05  M94                     PIC X(10) VALUE "刪除錯誤 !".
      05  M95                     PIC X(10) VALUE "處理中   !".
      05  M96                     PIC X(10) VALUE "處理完畢 !".
      05  M97                     PIC X(10) VALUE "確定(Y/N)?".
      05  M98                     PIC X(10) VALUE "輸入錯誤 !".
      05  M99                     PIC X(10) VALUE "處理正確 !".
*
 01   STU.
      05  STAT                    PIC 99.
          88  STAT-OK             VALUE   00 THRU 09.
          88  STAT-EOF            VALUE   10.
      05  STAT-R REDEFINES STAT   PIC 99.
  01  INDEX-G.
     05 X01                       PIC 9(4)  COMP.
     05 X02                       PIC 9(4)  COMP.
     05 X03                       PIC 9(4)  COMP.
     05 Y01                       PIC 9(4)  COMP.
     05 Y02                       PIC 9(4)  COMP.
     05 Y03                       PIC 9(4)  COMP.
     05 DUMMY                     PIC X.
*    05 ERR-FILE                  PIC X(08).
     05 H000A                     PIC 9(4)  COMP   VALUE 10.
     05 H000A-R  REDEFINES H000A.
        10 FILLER                 PIC X.
        10 H00A                   PIC X.
      05  LF-BUF.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
          10  FILLER              PIC 9(04) COMP VALUE 2570.
*    X98: PAGE CNT         X99: LINE CNT
 01  PRINTER-G.
     05 X97                       PIC 9(5) COMP VALUE 0.
     05 X98                       PIC 9(5) COMP VALUE 1.
     05 X99                       PIC 9(2) COMP VALUE 0.
 01  FLAG-G.
     05 F01                       PIC X  VALUE SPACES.
        88 F01-ON                 VALUE  "Y".
        88 F01-OFF                VALUE  "N".
     05 F02                       PIC X  VALUE SPACES.
        88 F02-ON                 VALUE  "Y".
        88 F02-OFF                VALUE  "N".
     05 F03                       PIC X  VALUE SPACES.
        88 F03-ON                 VALUE  "Y".
        88 F03-OFF                VALUE  "N".
     05 FLAG-FILE                 PIC X  VALUE SPACES.
        88  FILE-OFF              VALUE  "N", "n".
 01  FUNC-KEY-GROUP.
     05 CODE-CMD-KEY              PIC   99  COMP     VALUE 10.
     05 CODE-EOF-KEY              PIC   99  COMP     VALUE 99.
*
 01   MSG-FILE-R.
      05  REPLY-CODE-1            PIC 9(04) COMP.
      05  FILLER                  PIC X(02).
      05  WR-ADVISORY             PIC X(78).
      05  WCHK-G-R                PIC X(050).
 LINKAGE SECTION.
      COPY "CMN/LIB/MSG".
      02  MSG-BUF.
          05  MSG-CA1.
              10  CA03                           PIC  9(008)       COMP.
              10  CA36                           PIC  9(003)       COMP.
              10  CA37                           PIC  9(003)       COMP.
              10  CA40                           PIC  9(007)       COMP.
*             10  CA41                           PIC  9(006)       COMP.
*             10  CA42                           PIC  9(005)       COMP.
              10  CA48                           PIC  9(007)       COMP.
	  05  MSG-CA2.
              10  CA01                           PIC  X(020)           .
              10  CA02                           PIC  X(012)           .
              10  CA04                           PIC  X(010)           .
              10  CA05                           PIC  X(004)           .
              10  CA06                           PIC  X(007)           .
              10  CA07                           PIC  X(020)           .
              10  CA08                           PIC  X(001)           .
*              10  CA09                           PIC  X(003)           .
*              10  CA10                           PIC  X(020)           .
              10  CA11                           PIC  X(002)           .
              10  CA12                           PIC  X(020)           .
              10  CA13                           PIC  X(001)           .
              10  CA14                           PIC  X(001)           .
              10  CA15                           PIC  X(030)           .
              10  CA16                           PIC  X(020)           .
              10  CA17                           PIC  X(002)           .
              10  CA18                           PIC  X(010)           .
              10  CA19                           PIC  X(010)           .
              10  CA20                           PIC  X(010)           .
              10  CA21                           PIC  X(040)           .
              10  CA22                           PIC  X(040)           .
              10  CA23                           PIC  X(060)           .
              10  CA24                           PIC  X(060)           .
*             10  CA25                           PIC  X(040)           .
              10  CA26                           PIC  X(020)           .
              10  CA27                           PIC  X(020)           .
              10  CA28                           PIC  X(025)           .
              10  CA29                           PIC  X(060)           .
              10  CA30                           PIC  X(002)           .
              10  CA31                           PIC  X(020)           .
              10  CA32                           PIC  X(002)           .
              10  CA33                           PIC  X(020)           .
              10  CA34                           PIC  X(002)           .
              10  CA35                           PIC  X(020)           .
              10  CA38                           PIC  X(010)           .
              10  CA39                           PIC  X(020)           .
              10  CA43                           PIC  X(010)           .
              10  CA44                           PIC  X(001)           .
              10  CA45                           PIC  X(010)           .
              10  CA46                           PIC  X(001)           .
              10  CA47                           PIC  X(001)           .
              10  CA49                           PIC  X(001)           .
              10  CA50                           PIC  X(004)           .
              10  CA51                           PIC  X(001)           .
      02  COMM-LNK.
      COPY "CMN/LIB/COMMLNK".
*
      02  WCHK-G.
          10  WCHK-01         PIC X OCCURS  51 TIMES.
      02  WCHK-G0     REDEFINES   WCHK-G.
          10  WCHK-001        PIC X                    .
          10  WCHK-002        PIC X                    .
          10  WCHK-003        PIC X                    .
          10  WCHK-004        PIC X                    .
          10  WCHK-005        PIC X                    .
          10  WCHK-006        PIC X                    .
          10  WCHK-007        PIC X                    .
          10  WCHK-008        PIC X                    .
          10  WCHK-009        PIC X                    .
          10  WCHK-010        PIC X                    .
          10  WCHK-011        PIC X                    .
          10  WCHK-012        PIC X                    .
          10  WCHK-013        PIC X                    .
          10  WCHK-014        PIC X                    .
          10  WCHK-015        PIC X                    .
          10  WCHK-016        PIC X                    .
          10  WCHK-017        PIC X                    .
          10  WCHK-018        PIC X                    .
          10  WCHK-019        PIC X                    .
          10  WCHK-020        PIC X                    .
          10  WCHK-021        PIC X                    .
          10  WCHK-022        PIC X                    .
          10  WCHK-023        PIC X                    .
          10  WCHK-024        PIC X                    .
          10  WCHK-025        PIC X                    .
          10  WCHK-026        PIC X                    .
          10  WCHK-027        PIC X                    .
          10  WCHK-028        PIC X                    .
          10  WCHK-029        PIC X                    .
          10  WCHK-030        PIC X                    .
          10  WCHK-031        PIC X                    .
          10  WCHK-032        PIC X                    .
          10  WCHK-033        PIC X                    .
          10  WCHK-034        PIC X                    .
          10  WCHK-035        PIC X                    .
          10  WCHK-036        PIC X                    .
          10  WCHK-037        PIC X                    .
          10  WCHK-038        PIC X                    .
          10  WCHK-039        PIC X                    .
          10  WCHK-040        PIC X                    .
          10  WCHK-041        PIC X                    .
          10  WCHK-042        PIC X                    .
          10  WCHK-043        PIC X                    .
          10  WCHK-044        PIC X                    .
          10  WCHK-045        PIC X                    .
          10  WCHK-046        PIC X                    .
          10  WCHK-047        PIC X                    .
          10  WCHK-048        PIC X                    .
          10  WCHK-049        PIC X                    .
          10  WCHK-050        PIC X                    .
          10  WCHK-051        PIC X                    .
 PROCEDURE                        DIVISION USING MSG-G.
*
      COPY "CMN/LIB/DECL".
 MAIN SECTION.
*
 0000-MAIN.
      PERFORM 0100-INIT
      PERFORM 1000-PROC
      PERFORM 8600-CLOSE-ALL.
 0099-EXIT.
      CANCEL ALL.
      EXIT PROGRAM.
 0100-INIT.
      MOVE SYS-DATE-L TO WSDATE-R.
      ACCEPT      WSTIME  FROM    TIME
      MOVE        WS-HOUR TO      WS-HOUR-R
      MOVE        WS-MIN  TO      WS-MIN-R
      MOVE        WS-SEC  TO      WS-SEC-R.
      MOVE        "00"    TO      STAT
      PERFORM 0110-INIT.
      IF  NOT STAT-OK
          PERFORM 6500-CRT
          GO TO   0099-EXIT.
 0110-INIT.
      INITIALIZE  ORDVEND-R .
      IF  STAT-POPMVDR  NOT = "83"
      IF  STAT-OK
          PERFORM         8000-OPENS-ORDVEND .
      INITIALIZE  POPMVDR-R .
      IF  STAT-POPMVDR  NOT = "83"
      IF  STAT-OK
          PERFORM         8000-OPENS-POPMVDR .
      INITIALIZE  POPMVDN-R .
      IF  STAT-POPMVDN  NOT = "83"
      IF  STAT-OK
          PERFORM         8000-OPENS-POPMVDN .
      INITIALIZE  POPMMEN-R .
      IF  STAT-POPMMEN  NOT = "83"
      IF  STAT-OK
          PERFORM         8000-OPENI-POPMMEN .
      INITIALIZE  POPMCMP-R .
      IF  STAT-POPMCMP  NOT = "83"
      IF  STAT-OK
          PERFORM         8000-OPENI-POPMCMP .
      INITIALIZE  POPMCAR-R .
      IF  STAT-POPMCAR  NOT = "83"
      IF  STAT-OK
          PERFORM         8000-OPENI-POPMCAR .
      INITIALIZE  POPMLOC-R .
      IF  STAT-POPMLOC  NOT = "83"
      IF  STAT-OK
          PERFORM         8000-OPENI-POPMLOC .
      INITIALIZE  POPMPAY-R .
      IF  STAT-POPMPAY  NOT = "83"
      IF  STAT-OK
          PERFORM         8000-OPENI-POPMPAY .
      INITIALIZE  POPMPRI-R .
      IF  STAT-POPMPRI  NOT = "83"
      IF  STAT-OK
          PERFORM         8000-OPENI-POPMPRI .
      INITIALIZE  INCMBNK-R .
      IF  STAT-INCMBNK  NOT = "83"
      IF  STAT-OK
          PERFORM         8000-OPENI-INCMBNK .
*     INITIALIZE  IMSMSRT-R .
*     IF  STAT-IMSMSRT  NOT = "83"
*     IF  STAT-OK
*         PERFORM         8000-OPENI-IMSMSRT .
      IF  NOT STAT-OK
          PERFORM 5090-ERR.
 0150-INIT.
      MOVE    "00"        TO      STAT.
      IF  NOT STAT-OK
          PERFORM 5090-ERR.
* F1->INQUARY, F5->CLEAR, F6 -> ADD, F7 -> UPDATE, F9->DELETE
* PROCESS SECTION
*
 1000-PROC.
      START TRANSACTION.
      PERFORM 6000-GET
      IF  NOT CMD-KEY
          PERFORM 3000-MOVE
          PERFORM 0150-INIT.
      IF  INQ-KEY  OR   READ-KEY
          PERFORM  2500-PROC
      ELSE
      IF  ADD-KEY   OR  UPD-KEY OR      DEL-KEY
          PERFORM  1010-PROC.
      PERFORM 6500-CRT.
 1010-PROC.
      MOVE  "00"       TO   STAT.
      IF  NOT FILE-OFF    AND
          ( UPD-KEY OR    DEL-KEY )
          PERFORM 3000-MOVE
          PERFORM 8200-READL-POPMVDR .
      IF  NOT STAT-OK
          IF  UPD-KEY
              PERFORM  5093-ERR
          ELSE
          IF  DEL-KEY
              PERFORM  5094-ERR
          ELSE
              PERFORM  5089-ERR
      ELSE
          MOVE     SPACES    TO     WCHK-G
          MOVE     W-TOP     TO     X01
          PERFORM  3000-MOVE
          PERFORM  4000-CHK  UNTIL  X01 > W-BOTTOM OR EOF-KEY
          PERFORM  6520-CRT
          IF  ADD-KEY   OR  UPD-KEY OR  DEL-KEY
              PERFORM 3710-PROC
              IF  ADD-KEY
                  PERFORM  2100-PROC
              ELSE
              IF  UPD-KEY
                  PERFORM  2200-PROC
              ELSE
              IF  DEL-KEY
                  PERFORM  2300-PROC.
* ADD
 2100-PROC.
      MOVE "Y"        TO POPMVDR-MAIL-FLAG.
      IF POPMVDR-07 = SPACE
         MOVE POPMVDR-09 TO POPMVDR-07
      END-IF
      IF POPMVDR-39 = SPACE
         MOVE POPMVDR-07 TO POPMVDR-39
      END-IF
      IF  NOT FILE-OFF
          PERFORM 8300-WRITE-POPMVDR
      END-IF
      IF STAT-OK
*        PERFORM 9000-INSERT-ORDVEND
**--- add by Simon 95/01/19   ---**
         IF NOT (POPMVDR-DELETE = "Y" OR "y")
            PERFORM 8300-WRITE-POPMVDN
            IF NOT STAT-OK AND STAT = 22
               MOVE 998                TO REPLY-CODE
               MOVE STAT               TO ERR-MSG0
               MOVE POPMVDN-PK         TO ERR-KEY
               MOVE "廠商代號簡稱檔已存在" TO ERR-CALL
            END-IF
         END-IF
      ELSE
      IF STAT = 22
         MOVE 998                TO REPLY-CODE
         MOVE STAT               TO ERR-MSG0
         MOVE POPMVDR-PK         TO ERR-KEY
         MOVE "該廠商代號已存在" TO ERR-CALL
      END-IF
      END-IF
      IF  NOT STAT-OK   AND NOT FILE-OFF
                        AND (STAT NOT = 22)
          PERFORM    5092-ERR.
* UPDATE
 2200-PROC.
*      MOVE POPMVDR-07 TO POPMVDR-39
      IF POPMVDR-07 = SPACE
         MOVE POPMVDR-09 TO POPMVDR-07
      END-IF
      IF  NOT FILE-OFF
          PERFORM 8300-REWRITE-POPMVDR .
       IF STAT-OK
**--- add by Simon 95/01/19   ---**
          IF POPMVDR-DELETE = "Y" OR "y"
             PERFORM 8400-DELETE-POPMVDN
             IF STAT = "23"
                SET STAT-OK TO TRUE
             END-IF
          ELSE
             PERFORM 8300-REWRITE-POPMVDN
**--- add by Simon 89/04/14   ---**
             IF NOT STAT-OK
                PERFORM 8300-WRITE-POPMVDN.
**--- end of add by Simon 89/04/14   ---**

*      ELSEUNLOCK POPMVDN.
      IF  NOT STAT-OK   AND NOT FILE-OFF
          PERFORM    5093-ERR.
* DELETE
 2300-PROC.
      IF  NOT FILE-OFF
          PERFORM 8400-DELETE-POPMVDR .
       IF STAT-OK
          PERFORM 8400-DELETE-POPMVDN
**--- add by Simon 95/01/19   ---**
          IF STAT = "23"
             SET STAT-OK TO TRUE
          END-IF
       END-IF.
*      ELSEUNLOCK POPMVDN.
      IF  NOT STAT-OK   AND NOT FILE-OFF
          PERFORM     5094-ERR.
* INQUARY
 2500-PROC.
      PERFORM 3000-MOVE
      IF  READ-KEY
          PERFORM 8200-READN-POPMVDR       
*------------modify by Yihuei for 雲碼 102/04/30
          if level-id-l not = 0
             IF CMP-ID-L = "S "   AND 
                POPMVDR-38 NOT = CMP-ID-L
                MOVE "23" TO STAT
             ELSE
             IF CMP-ID-L NOT = "S "   AND 
                POPMVDR-38 NOT = "1 "
                MOVE "00" TO STAT
             END-IF
             END-IF
          end-if
      ELSE
      IF  INQ-KEY
          PERFORM 8101-POPMVDR-PK-POPMVDR
          IF  STAT-OK
              PERFORM 8200-READS-POPMVDR
*------------modify by Yihuei for 雲碼 102/04/30
              if level-id-l = 0
                 MOVE "00" TO STAT
              else
                 IF STAT-OK AND CMP-ID-L = "S "   
                            AND POPMVDR-38 = CMP-ID-L
                    MOVE 00 TO STAT
                 ELSE
                 IF STAT-OK AND CMP-ID-L NOT = "S "   
                            AND POPMVDR-38 = "1 "
                    MOVE 00 TO STAT
                 ELSE
                    MOVE "10"   TO STAT.
      IF  STAT-OK
          MOVE     SPACES    TO     WCHK-G
          MOVE     W-TOP     TO     X01
          PERFORM  4000-CHK  UNTIL  X01 > W-BOTTOM OR EOF-KEY
          PERFORM 3710-PROC
      ELSE
      IF  STAT-EOF
          PERFORM     5091-ERR
      ELSE
          PERFORM     5089-ERR.
      MOVE W-TOP  TO X01.
*
* MOVEMENT SECTION
*
* PUSH ITEM
 3000-MOVE.
      MOVE    CA05
          TO  POPMVDR-01                         .
      if cmp-id-l = "S " and ca05 = spaces
         move "SA  " to popmvdr-01
      end-if
*      MOVE    CA06
*          TO  POPMVDR-02                         .
      MOVE    CA06
          TO  POPMVDR-29                         .
      MOVE    CA07
          TO  POPMVDR-33                         .
      MOVE    CA08
          TO  POPMVDR-06                         .
*      MOVE    CA09
*          TO  POPMVDR-03                         .
      MOVE    CA11
          TO  POPMVDR-05                         .
      MOVE    CA13
          TO  POPMVDR-37                         .
      MOVE    CA14
          TO  POPMVDR-20                         .
      MOVE    CA15
          TO  POPMVDR-18                         .
      MOVE    CA16
          TO  POPMVDR-19                         .
*      MOVE    CA17
*          TO  POPMVDR-38                         .
      MOVE    CA19
          TO  POPMVDR-09                         .
      MOVE    CA20
          TO  POPMVDR-10                         .
      MOVE    CA21
          TO  POPMVDR-07                         .
      MOVE    CA43
          TO  POPMVDR-07-1                       .
      MOVE    CA22
          TO  POPMVDR-08                         .
      MOVE    CA23  TO  POPMVDR-ADD-1.
      MOVE    CA24  TO  POPMVDR-ADD-2.
*     MOVE    CA23
*         TO  POPMVDR-111                        .
*     MOVE    CA24
*         TO  POPMVDR-112                        .
*     MOVE    CA25
*         TO  POPMVDR-113                        .
      MOVE    CA26
          TO  POPMVDR-14                         .
      MOVE    CA27
          TO  POPMVDR-15                         .
      MOVE    CA29
          TO  POPMVDR-39                         .
*      MOVE    CA28
*          TO  POPMVDR-16                         .
*      MOVE    CA29
*          TO  POPMVDR-17                         .
      MOVE    CA30
          TO  POPMVDR-24                         .
      MOVE    CA32
          TO  POPMVDR-25                         .
      MOVE    CA34
          TO  POPMVDR-26                         .
      MOVE    CA36
          TO  POPMVDR-27                         .
      MOVE    CA37
          TO  POPMVDR-28                         .
      MOVE    CA38
          TO  POPMVDR-12                         .
      MOVE    CA39
          TO  POPMVDR-13                         .
      MOVE    CA40
          TO  POPMVDR-21                         .
*      MOVE    CA41
*          TO  POPMVDR-22                         .
*      MOVE    CA42
*          TO  POPMVDR-23                         .
      MOVE    CA44
          TO  POPMVDR-MAIL-FLAG                  .
      MOVE    CA45
          TO  POPMVDR-MAIL-CODE                  .
      MOVE    CA46
          TO  POPMVDR-DELETE                     .
      MOVE    CA47
          TO  POPMVDR-RELATION                   .
      MOVE    CA49
          TO  POPMVDR-32(40:1)                   .
      MOVE    CA48
          TO  POPMVDR-UPD-DATE                   .
      MOVE    CA51
          TO  POPMVDR-30(40:1)                   .    
*------------modify by Yihuei for 雲碼 102/04/30
      IF CMP-ID-L = "S "
         MOVE CMP-ID-L   TO  CA17   POPMVDR-38
      ELSE
         MOVE "1 "       TO  CA17   POPMVDR-38
      END-IF.
* POP  ITEM
 3010-MOVE.
      MOVE    CMP-NAME-L
          TO  CA01                               .
      MOVE    TERM-ID-L
          TO  CA02                               .
      MOVE    USER-NAME-L
          TO  CA04                               .
      MOVE    POPMVDR-01
          TO  CA05                               .
      MOVE    POPMVDR-29
          TO  CA06                               .
      MOVE    POPMVDR-33
          TO  CA07                               .
*      MOVE    POPMMEN-03
*          TO  CA07                               .
      MOVE    POPMVDR-06
          TO  CA08                               .
*      MOVE    POPMVDR-03
*          TO  CA09                               .
*     MOVE    IMSMSRT-02
*         TO  CA10                               .
      MOVE    POPMVDR-05
          TO  CA11                               .
      MOVE    POPMLOC-02
          TO  CA12                               .
      MOVE    POPMVDR-37
          TO  CA13                               .
      MOVE    POPMVDR-20
          TO  CA14                               .
      MOVE    POPMVDR-18
          TO  CA15                               .
      MOVE    POPMVDR-19
          TO  CA16                               .
      MOVE    POPMVDR-38
          TO  CA17                               .
      MOVE    POPMCMP-04
          TO  CA18                               .
      MOVE    POPMVDR-09
          TO  CA19                               .
      MOVE    POPMVDR-10
          TO  CA20                               .
      MOVE    POPMVDR-07
          TO  CA21                               .
      MOVE    POPMVDR-07-1
          TO  CA43                               .
      MOVE    POPMVDR-08
          TO  CA22                               .
      MOVE    POPMVDR-ADD-1  TO  CA23.
      MOVE    POPMVDR-ADD-2  TO  CA24.
*     MOVE    POPMVDR-111
*         TO  CA23                               .
*     MOVE    POPMVDR-112
*         TO  CA24                               .
*     MOVE    POPMVDR-113
*         TO  CA25                               .
      MOVE    POPMVDR-14
          TO  CA26                               .
      MOVE    POPMVDR-15
          TO  CA27                               .
      MOVE    INCMBNK-NAME
          TO  CA28                               .
      MOVE    POPMVDR-39
          TO  CA29                               .
      MOVE    POPMVDR-24
          TO  CA30                               .
      MOVE    POPMCAR-02
          TO  CA31                               .
      MOVE    POPMVDR-25
          TO  CA32                               .
      MOVE    POPMPAY-02
          TO  CA33                               .
      MOVE    POPMVDR-26
          TO  CA34                               .
      MOVE    POPMPRI-02
          TO  CA35                               .
      MOVE    POPMVDR-27
          TO  CA36                               .
      MOVE    POPMVDR-28
          TO  CA37                               .
      MOVE    POPMVDR-12
          TO  CA38                               .
      MOVE    POPMVDR-13
          TO  CA39                               .
      MOVE    POPMVDR-21
          TO  CA40                               .
*      MOVE    POPMVDR-22
*          TO  CA41                               .
*      MOVE    POPMVDR-23
*          TO  CA42                               .
      MOVE    POPMVDR-MAIL-FLAG
          TO  CA44                               .
      MOVE    POPMVDR-MAIL-CODE
          TO  CA45                               .
      MOVE    POPMVDR-DELETE
          TO  CA46                               .
      MOVE    POPMVDR-RELATION
          TO  CA47                               .
      if popmvdr-upd-date = spaces
         move 0 to ca48
      else
         MOVE POPMVDR-UPD-DATE TO  CA48                               
      end-if.
      MOVE    POPMVDR-32(40:1)
          TO  CA49                               .
      MOVE    POPMVDR-30(40:1) TO  CA51.     
      IF POPMVDR-32(40:1) = "L"
         MOVE "國內"   TO  CA50
      ELSE
         IF POPMVDR-32(40:1) = "F"
            MOVE "國外"   TO  CA50
         ELSE
            IF POPMVDR-32(40:1) = "P"
               MOVE "個人"   TO  CA50
            ELSE  
               MOVE "其他"   TO  CA50        
            END-IF
         END-IF
      END-IF.
 3710-PROC.
      MOVE POPMVDR-01 TO POPMVDN-01 .
*------------modify by Yihuei for 雲碼 102/04/30
      IF CMP-ID-L = "S "
         MOVE CMP-ID-L   TO POPMVDN-CMP-ID
      ELSE
         MOVE "1 "       TO POPMVDN-CMP-ID
      END-IF
      IF UPD-KEY OR DEL-KEY
         PERFORM 8200-READL-POPMVDN   .
      IF POPMVDR-09 NOT = SPACES
         MOVE POPMVDR-09 TO POPMVDN-02
      ELSE MOVE POPMVDR-10 TO POPMVDN-02 .
      MOVE POPMVDR-29 TO INCMBNK-ID
      PERFORM 8200-READN-INCMBNK
      IF STAT-OK
         MOVE INCMBNK-NAME TO CA28
      ELSE
         MOVE SPACES       TO CA28
      END-IF.
*
* CHECK SECTION
*
 4000-CHK.
      IF  X01 =   005
          PERFORM 4105-CHK
      ELSE
      IF  X01 =   006
          PERFORM 4106-CHK
      ELSE
*B加強對銀行帳號檢核  20191030 BY RICK   *      
      IF  X01 =   007
          PERFORM 4107-CHK
      ELSE
*E加強對銀行帳號檢核  20191030 BY RICK  *     
      IF  X01 =   008
          PERFORM 4108-CHK
      ELSE
      IF  X01 =   009
          PERFORM 4109-CHK
      ELSE
      IF  X01 =   011
          PERFORM 4111-CHK
      ELSE
      IF  X01 =   013
          PERFORM 4113-CHK
      ELSE
      IF  X01 =   014
          PERFORM 4114-CHK
      ELSE
      IF  X01 =   017
          PERFORM 4117-CHK
      ELSE
      IF  X01 =   029
          PERFORM 4129-CHK
      ELSE
      IF  X01 =   030
          PERFORM 4130-CHK
      ELSE
      IF  X01 =   032
          PERFORM 4132-CHK
      ELSE
      IF  X01 =   034
          PERFORM 4134-CHK
      ELSE
      IF  X01 =   038
          PERFORM 4138-CHK    
      ELSE
      IF  X01 =   040
          PERFORM 4140-CHK
      ELSE
      IF  X01 =   041
          PERFORM 4141-CHK
      ELSE
      IF  X01 =   046
          PERFORM 4146-CHK
      ELSE
      IF  X01 =   049
          PERFORM 4149-CHK 
      ELSE
      IF  X01 =   051
          PERFORM 4151-CHK
      ELSE     
      IF  X01 <   W-TOP
          MOVE    W-BOTTOM        TO      X01.
      ADD     1               TO      X01.
 4105-CHK.
      MOVE POPMVDR-01 TO POPMVDR-011.
      IF  NOT ( POPMVDR-01 NOT = SPACES)
          MOVE    "!"     TO      WCHK-01(005) 
      END-IF
*------------------------------------------------------
      IF CMP-ID-L NOT = "S "         
         IF POPMVDR-01 >= "SA00" AND
            POPMVDR-01 <= "SZZZ" 
            MOVE 998                TO REPLY-CODE
            MOVE POPMVDR-PK         TO ERR-MSG0
            MOVE "此廠商代號不屬於所登入公司" TO ERR-MSG1
            PERFORM 8600-CLOSE-ALL
            PERFORM 6500-CRT
            GO TO 0099-EXIT
         END-IF   
      ELSE
      IF CMP-ID-L = "S "         
         IF NOT ( POPMVDR-01 >= "SA00" AND
                  POPMVDR-01 <= "SZZZ" )
            MOVE 998                TO REPLY-CODE
            MOVE POPMVDR-PK         TO ERR-MSG0
            MOVE "此廠商代號不屬於所登入公司" TO ERR-MSG1
            PERFORM 8600-CLOSE-ALL
            PERFORM 6500-CRT
            GO TO 0099-EXIT
         END-IF   
      END-IF      
      END-IF.
 4106-CHK.
      MOVE POPMVDR-02 TO POPMMEN-01 .
      PERFORM 8200-READN-POPMMEN   .
      IF NOT STAT-OK MOVE SPACES TO POPMMEN-03
      ELSE  IF POPMMEN-02 NOT = SPACES
               MOVE POPMMEN-02 TO POPMMEN-03 .
      IF  NOT ( (POPMVDR-02 = SPACES) OR VALID-POPMMEN)
          MOVE    "!"     TO      WCHK-01(006).
*B加強對銀行帳號檢核  20191030 BY RICK ----------------  *    
 4107-CHK.
      SET     FLAG-SW-01-NUMERIC             TO TRUE.
      MOVE    POPMVDR-33                     TO WK-POPMVDR-33
      PERFORM VARYING X02 FROM 1  BY 1
        UNTIL FLAG-SW-01-ERR 
           OR X02  > 20
           
        IF    WK-POPMVDR-33-01 (X02) IS NUMERIC
              IF   FLAG-SW-01-NONNUM  
                   SET  FLAG-SW-01-ERR      TO TRUE
                   MOVE "!"                 TO WCHK-01(007) 
                   
              END-IF     
        ELSE
              IF   WK-POPMVDR-33-01 (X02)   = SPACE
                   IF   FLAG-SW-01-NUMERIC
                        SET  FLAG-SW-01-NONNUM   
                                            TO TRUE
                   END-IF
              ELSE 
                   SET  FLAG-SW-01-ERR      TO TRUE 
                   MOVE "!"                 TO WCHK-01(007)
              END-IF 
        END-IF           
      END-PERFORM. 
*      MOVE "!"                 TO WCHK-01(007). 
*E加強對銀行帳號檢核  20191030 BY RICK ----------------  *           
 4108-CHK.
      IF  NOT ( POPMVDR-06 = "1" OR "2" OR "3" OR "4" OR " ")
          MOVE    "!"     TO      WCHK-01(008).
 4109-CHK.
       MOVE  POPMVDR-03 TO POPMVDR-031 .
*      MOVE POPMVDR-03 TO IMSMSRT-01.
*         PERFORM 8200-READN-IMSMSRT.
*     IF NOT STAT-OK MOVE SPACES TO IMSMSRT-02 .
*     IF  NOT ( (POPMVDR-03 = SPACES) OR VALID-IMSMSRT)
      IF  NOT (POPMVDR-03 = SPACES)
          MOVE    "!"     TO      WCHK-01(009).
 4111-CHK.
         MOVE POPMVDR-05 TO POPMLOC-01 .
          PERFORM 8200-READN-POPMLOC   .
         IF NOT STAT-OK MOVE SPACES TO POPMLOC-02 .
      IF  NOT ( (POPMVDR-05 = SPACES) OR VALID-POPMLOC)
          MOVE    "!"     TO      WCHK-01(011).
 4113-CHK.
      IF  NOT ( POPMVDR-37 = "1" OR "9" OR " ")
          MOVE    "!"     TO      WCHK-01(013).
 4114-CHK.
      IF  NOT ( POPMVDR-20 = "D" OR " ")
          MOVE    "!"     TO      WCHK-01(014).
 4117-CHK.
       MOVE POPMVDR-38 TO POPMCMP-01.
          PERFORM 8200-READN-POPMCMP.
       IF NOT STAT-OK MOVE SPACES TO POPMCMP-04
       ELSE IF POPMCMP-04 = SPACES
               MOVE POPMCMP-05 TO POPMCMP-04.
*      IF  NOT ( (POPMVDR-38 = SPACES) OR VALID-POPMCMP)
*          MOVE    "!"     TO      WCHK-01(017).
 4129-CHK.
         IF      POPMVDR-29   = SPACES
                 NEXT SENTENCE
         ELSE
                 MOVE    POPMVDR-29     TO INCMBNK-ID 
                 PERFORM 8200-READN-INCMBNK 
                 IF      NOT STAT-OK 
                         MOVE    "!"     TO      WCHK-01(029)
                 END-IF
         END-IF.
 4130-CHK.
         MOVE POPMVDR-24 TO POPMCAR-01.
          PERFORM 8200-READN-POPMCAR.
         IF NOT STAT-OK MOVE SPACES TO POPMCAR-02
         ELSE
         IF POPMCAR-02 = SPACES
            MOVE POPMCAR-03 TO POPMCAR-02 .
      IF  NOT ( (POPMVDR-24 = SPACES) OR VALID-POPMCAR)
          MOVE    "!"     TO      WCHK-01(030).
 4132-CHK.
         MOVE POPMVDR-25 TO POPMPAY-01.
          PERFORM 8200-READN-POPMPAY.
         IF NOT STAT-OK MOVE SPACES TO POPMPAY-02
         ELSE IF POPMPAY-02 = SPACES
                 MOVE POPMPAY-03 TO POPMPAY-02 .
      IF  NOT ( POPMVDR-25 = SPACES OR VALID-POPMPAY)
          MOVE    "!"     TO      WCHK-01(032).
 4134-CHK.
         MOVE POPMVDR-26 TO POPMPRI-01
          PERFORM 8200-READN-POPMPRI
         IF NOT STAT-OK MOVE SPACES TO POPMPRI-02
         ELSE IF POPMPRI-02 = SPACES
                 MOVE POPMPRI-03 TO POPMPRI-02 .
      IF  NOT ( POPMVDR-26 = SPACES OR VALID-POPMPRI)
          MOVE    "!"     TO      WCHK-01(034). 
 4138-CHK.
      MOVE    POPMVDR-01                      TO WK-POPMVDR-01 
      MOVE    POPMVDR-12                      TO WK-POPMVDR-12 
      MOVE    POPMVDR-DELETE                  TO WK-POPMVDR-DELETE
      EVALUATE TRUE
          WHEN WK-POPMVDR-12    =  SPACES
               MOVE    "00"                           TO STAT
          WHEN ADD-KEY 
               PERFORM 8100-POPMVDR-AK2-POPMVDR 
               PERFORM 8200-READS-POPMVDR-AK2  
               PERFORM UNTIL POPMVDR-12 NOT = WK-POPMVDR-12   
                          OR END-POPMVDR  
                       
                       IF      STAT-OK                       AND
                               POPMVDR-38       = CMP-ID-L   AND 
                               POPMVDR-DELETE   = SPACES 
                               MOVE    "!"             TO WCHK-01(038) 
                               MOVE     POPMVDR-PK     TO WK-ERR-MSG0
                               MOVE    "10"            TO STAT-POPMVDR
                       ELSE
                               MOVE    "00"            TO STAT  
                       END-IF 
                       PERFORM 8200-READS-POPMVDR-AK2  
               END-PERFORM  
               PERFORM 3000-MOVE         
          WHEN UPD-KEY 
               PERFORM 8100-POPMVDR-AK2-POPMVDR 
               PERFORM 8200-READS-POPMVDR-AK2
               PERFORM UNTIL POPMVDR-12 NOT = WK-POPMVDR-12   
                          OR END-POPMVDR   
                             
                       IF    POPMVDR-01       NOT = WK-POPMVDR-01    AND
                             POPMVDR-12           = WK-POPMVDR-12    AND
                             POPMVDR-38           = CMP-ID-L         AND
                             POPMVDR-DELETE       = SPACES   
                             MOVE    "!"             TO WCHK-01(038) 
                             MOVE    POPMVDR-PK      TO WK-ERR-MSG0
                             MOVE    "10"            TO STAT-POPMVDR
                       ELSE      
                             MOVE    "00"            TO STAT 
                       END-IF
                       PERFORM 8200-READS-POPMVDR-AK2 
               END-PERFORM  
               PERFORM 3000-MOVE   
      END-EVALUATE. 
                      
 4140-CHK.
      IF POPMVDR-21 = ZEROS
         MOVE "N" TO FLAG-ERROR
      ELSE
         MOVE POPMVDR-21 TO DATE-YMD
         PERFORM 9000-EXP
      END-IF .
      IF  NOT ( POPMVDR-21 = ZEROS OR FLAG-ERROR-OFF)
          MOVE    "!"     TO      WCHK-01(040).
 4141-CHK.
 4146-CHK.
      IF  NOT ( POPMVDR-DELETE   = "Y" OR " ")
          MOVE    "!"     TO      WCHK-01(046).
 4147-CHK.
      IF  NOT ( POPMVDR-RELATION = "Y" OR " ")
          MOVE    "!"     TO      WCHK-01(047).
 4149-CHK.
** 國內(Local)  : POPMVDR-01(1:1) BETWEEN 0-9 & POPMVDR-12(1:1) BETWEEN 0-9 
** 個人(Person) :POPMVDR-01(1:1) BETWEEN 0-9 & POPMVDR-12(1:1) BETWEEN A-Z 
** 國外(Forigen): POPMVDR-01(1:1) BETWEEN A-Z                               
** 其他('')
      IF POPMVDR-32(40:1) = " " 
         IF POPMVDR-01(1:1) >= "1" AND POPMVDR-01(1:1) <= "9" 
            IF POPMVDR-12(1:1) >= "0" AND POPMVDR-12(1:1) <= "9" 
               MOVE "L"   TO  POPMVDR-32(40:1)
            ELSE
               IF POPMVDR-12(1:1) >= "0" AND POPMVDR-12(1:1) <= "9" 
                  MOVE "P"   TO  POPMVDR-32(40:1)
               ELSE
                  MOVE " "   TO  POPMVDR-32(40:1)
               END-IF
            END-IF
         ELSE
            IF POPMVDR-01(1:1) >= "A" AND POPMVDR-01(1:1) <= "Z" 
               MOVE "F"   TO  POPMVDR-32(40:1)
            END-IF
         END-IF
      END-IF.
      IF  NOT ( POPMVDR-32(40:1) = "L" OR "F" OR "P" OR " ")
          MOVE    "!"     TO      WCHK-01(049). 
 4910-CHK.
 4151-CHK.
       IF      CA51    =  "Y"    OR  " " 
               NEXT SENTENCE
       ELSE
               MOVE "!"                 TO WCHK-01(051)
       END-IF.  
* 
*
* ERROR SECTION
*
      COPY "CMN/LIB/ERRPROC".
 6000-GET.
      MOVE    0               TO      REPLY-CODE.
 6500-CRT.
      IF  REPLY-CODE = 0
          PERFORM 3010-MOVE
          COMMIT TRANSACTION
      ELSE
          ROLLBACK TRANSACTION.
 6520-CRT.
      IF  WCHK-G  NOT =   SPACES
          PERFORM 6522-CRT
          MOVE    CODE-EOF-KEY    TO      EVENT
          MOVE    WCHK-G   TO   WCHK-G-R
          PERFORM 5098-ERR.
 6522-CRT.
      MOVE    "輸入錯誤 !"    TO  ERR-MSG0.
      IF  WCHK-01(005)    NOT =   SPACES
         MOVE "廠商代號不得為空白 !!!"
                                  TO      ERR-MSG1
      ELSE
      IF  WCHK-01(006)    NOT =   SPACES
         MOVE "採 購 員 不 存 在 !!!"
                                  TO      ERR-MSG1
      ELSE
*B加強對銀行帳號檢核  20191030 BY RICK ----------------  *       
      IF  WCHK-01(007)    NOT =   SPACES
          MOVE "受款人帳號需為數字 !!!"
                                  TO      ERR-MSG1
      ELSE
*E加強對銀行帳號檢核  20191030 BY RICK ----------------  *       
      IF  WCHK-01(008)    NOT =   SPACES
         MOVE "請 輸 入 1 到 4 !!!"
                                  TO      ERR-MSG1
      ELSE
      IF  WCHK-01(009)    NOT =   SPACES
         MOVE "供 貨 分 類 別 不 存 在 !!!"
                                  TO      ERR-MSG1
      ELSE
      IF  WCHK-01(011)    NOT =   SPACES
         MOVE "區 域 別 輸 入 錯 誤 !!!"
                                  TO      ERR-MSG1
      ELSE
      IF  WCHK-01(013)    NOT =   SPACES
         MOVE "請 輸 入 1 或 9 !!!"
                                  TO      ERR-MSG1
      ELSE
      IF  WCHK-01(014)    NOT =   SPACES
         MOVE "請 輸 入 空 白 或 D !!!"
                                  TO      ERR-MSG1
      ELSE
      IF  WCHK-01(017)    NOT =   SPACES
         MOVE "歸 屬 公 司 必 須 存 在 !!!"
                                  TO      ERR-MSG1
      ELSE
      IF  WCHK-01(029)    NOT =   SPACES
         MOVE "INCMBNK銀行主檔無此銀行代號!!!"
                                  TO      ERR-MSG1
      ELSE
      IF  WCHK-01(030)    NOT =   SPACES
         MOVE "運 輸 方 式 錯 誤 !!!"
                                  TO      ERR-MSG1
      ELSE
      IF  WCHK-01(032)    NOT =   SPACES
         MOVE "付 款 方 式 錯 誤 !!!"
                                  TO      ERR-MSG1
      ELSE
      IF  WCHK-01(038)    NOT =   SPACES
          MOVE WK-ERR-MSG0        TO ERR-MSG0
          MOVE "該筆資料統編重複" TO ERR-MSG1 
      ELSE
      IF  WCHK-01(040)    NOT =   SPACES
         MOVE "起始往來日 輸 入 有 誤 !!!"
                                  TO      ERR-MSG1
      ELSE
      IF  WCHK-01(046)    NOT =   SPACES
         MOVE "是否刪除必須為 Y 或空白!!"
                                  TO      ERR-MSG1
      ELSE
      IF  WCHK-01(047)    NOT =   SPACES
         MOVE "關係人否必須為 Y 或空白!!"
                                  TO      ERR-MSG1
      ELSE
      IF  WCHK-01(049)    NOT =   SPACES
         MOVE "請輸入廠商類別(國內L/國外F/個人P)!!"
                                  TO      ERR-MSG1
      ELSE
      IF  WCHK-01(051)    NOT =   SPACES
         MOVE "Rebate廠商必須為 Y 或空白!!"
                                  TO      ERR-MSG1                            
      ELSE
          NEXT    SENTENCE                                       .
*
* FILE I/O SECTION
*
 8000-OPENS-ORDVEND .
      OPEN    I-O     ORDVEND       .
      MOVE    STAT    TO      STAT-ORDVEND .
      IF  NOT STAT-OK
          MOVE        "ORDVEND "          TO  ERR-FILE.
 8000-OPENS-POPMVDR .
      OPEN    I-O     POPMVDR       .
      MOVE    STAT    TO      STAT-POPMVDR .
      IF  NOT STAT-OK
          MOVE        "POPMVDR "          TO  ERR-FILE.
 8000-OPENS-POPMVDN .
      OPEN    I-O     POPMVDN       .
      MOVE    STAT    TO      STAT-POPMVDN .
      IF  NOT STAT-OK
          MOVE        "POPMVDN "          TO  ERR-FILE.
 8000-OPENI-POPMMEN .
      OPEN    INPUT   POPMMEN       .
      MOVE    STAT    TO      STAT-POPMMEN .
      IF  NOT STAT-OK
          MOVE        "POPMMEN "          TO  ERR-FILE.
 8000-OPENI-POPMCMP .
      OPEN    INPUT   POPMCMP       .
      MOVE    STAT    TO      STAT-POPMCMP .
      IF  NOT STAT-OK
          MOVE        "POPMCMP "          TO  ERR-FILE.
 8000-OPENI-POPMCAR .
      OPEN    INPUT   POPMCAR       .
      MOVE    STAT    TO      STAT-POPMCAR .
      IF  NOT STAT-OK
          MOVE        "POPMCAR "          TO  ERR-FILE.
 8000-OPENI-POPMLOC .
      OPEN    INPUT   POPMLOC       .
      MOVE    STAT    TO      STAT-POPMLOC .
      IF  NOT STAT-OK
          MOVE        "POPMLOC "          TO  ERR-FILE.
 8000-OPENI-POPMPAY .
      OPEN    INPUT   POPMPAY       .
      MOVE    STAT    TO      STAT-POPMPAY .
      IF  NOT STAT-OK
          MOVE        "POPMPAY "          TO  ERR-FILE.
 8000-OPENI-POPMPRI .
      OPEN    INPUT   POPMPRI       .
      MOVE    STAT    TO      STAT-POPMPRI .
      IF  NOT STAT-OK
          MOVE        "POPMPRI "          TO  ERR-FILE.
 8000-OPENI-INCMBNK .
      OPEN    INPUT   INCMBNK       .
      MOVE    STAT    TO      STAT-INCMBNK .
      IF  NOT STAT-OK
          MOVE        "INCMBNK "          TO  ERR-FILE.
*8000-OPENI-IMSMSRT .
*     OPEN    INPUT   IMSMSRT       .
*     MOVE    STAT    TO      STAT-IMSMSRT .
*     IF  NOT STAT-OK
*         MOVE        "IMSMSRT "          TO  ERR-FILE.
*     IF  STAT-OK
*         ENTER   "COBOLFILEINFO" OF      COBOL-LIBRARY
*                 USING   IMSMSRT  ERR-CODE   OMITTED FILE-NO
*         ENTER   "SETMODE"
*                 USING   FILE-NO FUNC-CODE   PARAM-CODE1 PARAM-CODE2.
 8100-POPMVDR-PK-POPMVDR.
      START POPMVDR  KEY IS NOT < POPMVDR-PK
                  .
      MOVE    STAT    TO      STAT-POPMVDR .
      IF  NOT STAT-OK
          MOVE        "POPMVDR "          TO  ERR-FILE.
 8101-POPMVDR-PK-POPMVDR.
      START   POPMVDR  KEY IS >    POPMVDR-PK
                  .
      MOVE    STAT    TO      STAT-POPMVDR .
      IF  NOT STAT-OK
          MOVE        "POPMVDR "          TO  ERR-FILE.
 8100-POPMVDR-AK2-POPMVDR.
      START   POPMVDR  KEY IS NOT < POPMVDR-AK2.
      MOVE    STAT    TO      STAT-POPMVDR .         
 8200-READS-POPMVDR.
      READ POPMVDR  NEXT
                  .
      MOVE    STAT    TO      STAT-POPMVDR .
      IF  NOT STAT-OK
          MOVE        "POPMVDR "          TO  ERR-FILE.
      perform until not stat-ok or popmvdr-38 = cmp-id-l
         go to 8200-reads-popmvdr
      end-perform.
 8200-READS-POPMVDR-AK2.
      READ    POPMVDR  NEXT .
      MOVE    STAT                   TO STAT-POPMVDR . 
      IF      NOT STAT-OK
              MOVE   "POPMVDR "      TO ERR-FILE
      END-IF.        
                  
 8200-READS-POPMVDN.
      READ POPMVDN  NEXT
                  .
      MOVE    STAT    TO      STAT-POPMVDN .
      IF  NOT STAT-OK
          MOVE        "POPMVDN "          TO  ERR-FILE.
 8200-READS-POPMMEN.
      READ POPMMEN  NEXT
                  .
      MOVE    STAT    TO      STAT-POPMMEN .
      IF  NOT STAT-OK
          MOVE        "POPMMEN "          TO  ERR-FILE.
 8200-READS-POPMCMP.
      READ POPMCMP  NEXT
                  .
      MOVE    STAT    TO      STAT-POPMCMP .
      IF  NOT STAT-OK
          MOVE        "POPMCMP "          TO  ERR-FILE.
 8200-READS-POPMCAR.
      READ POPMCAR  NEXT
                  .
      MOVE    STAT    TO      STAT-POPMCAR .
      IF  NOT STAT-OK
          MOVE        "POPMCAR "          TO  ERR-FILE.
 8200-READS-POPMLOC.
      READ POPMLOC  NEXT
                  .
      MOVE    STAT    TO      STAT-POPMLOC .
      IF  NOT STAT-OK
          MOVE        "POPMLOC "          TO  ERR-FILE.
 8200-READS-POPMPAY.
      READ POPMPAY  NEXT
                  .
      MOVE    STAT    TO      STAT-POPMPAY .
      IF  NOT STAT-OK
          MOVE        "POPMPAY "          TO  ERR-FILE.
 8200-READS-POPMPRI.
      READ POPMPRI  NEXT
                  .
      MOVE    STAT    TO      STAT-POPMPRI .
      IF  NOT STAT-OK
          MOVE        "POPMPRI "          TO  ERR-FILE.
*8200-READS-IMSMSRT.
*     READ IMSMSRT  NEXT
*                 .
*     MOVE    STAT    TO      STAT-IMSMSRT .
*     IF  NOT STAT-OK
*         MOVE        "IMSMSRT "          TO  ERR-FILE.
 8200-READN-POPMVDR.
      READ POPMVDR
                  .
      MOVE    STAT    TO      STAT-POPMVDR .
      IF  NOT STAT-OK
          MOVE        "POPMVDR "          TO  ERR-FILE.   
 8200-READN-POPMVDN.
      READ POPMVDN
                  .
      MOVE    STAT    TO      STAT-POPMVDN .
      IF  NOT STAT-OK
          MOVE        "POPMVDN "          TO  ERR-FILE.
 8200-READN-POPMMEN.
      READ POPMMEN
                  .
      MOVE    STAT    TO      STAT-POPMMEN .
      IF  NOT STAT-OK
          MOVE        "POPMMEN "          TO  ERR-FILE.
 8200-READN-POPMCMP.
      READ POPMCMP
                  .
      MOVE    STAT    TO      STAT-POPMCMP .
      IF  NOT STAT-OK
          MOVE        "POPMCMP "          TO  ERR-FILE.
 8200-READN-POPMCAR.
      READ POPMCAR
                  .
      MOVE    STAT    TO      STAT-POPMCAR .
      IF  NOT STAT-OK
          MOVE        "POPMCAR "          TO  ERR-FILE.
 8200-READN-POPMLOC.
      READ POPMLOC
                  .
      MOVE    STAT    TO      STAT-POPMLOC .
      IF  NOT STAT-OK
          MOVE        "POPMLOC "          TO  ERR-FILE.
 8200-READN-POPMPAY.
      READ POPMPAY
                  .
      MOVE    STAT    TO      STAT-POPMPAY .
      IF  NOT STAT-OK
          MOVE        "POPMPAY "          TO  ERR-FILE.
 8200-READN-POPMPRI.
      READ POPMPRI
                  .
      MOVE    STAT    TO      STAT-POPMPRI .
      IF  NOT STAT-OK
          MOVE        "POPMPRI "          TO  ERR-FILE.
 8200-READN-INCMBNK.
      READ INCMBNK
                  .
      MOVE    STAT    TO      STAT-INCMBNK .
      IF  NOT STAT-OK
          MOVE        "INCMBNK "          TO  ERR-FILE.
*8200-READN-IMSMSRT.
*     READ IMSMSRT
*                 .
*     MOVE    STAT    TO      STAT-IMSMSRT .
*     IF  NOT STAT-OK
*         MOVE        "IMSMSRT "          TO  ERR-FILE.
 8200-READL-POPMVDR.
      READ POPMVDR  WITH LOCK
                  .
      MOVE    STAT    TO      STAT-POPMVDR .
      IF  NOT STAT-OK
          MOVE        "POPMVDR "          TO  ERR-FILE.
 8200-READL-POPMVDN.
      READ POPMVDN  WITH LOCK
                  .
      MOVE    STAT    TO      STAT-POPMVDN .
      IF  NOT STAT-OK
          MOVE        "POPMVDN "          TO  ERR-FILE.
 8200-READL-POPMMEN.
      READ POPMMEN  WITH LOCK
                  .
      MOVE    STAT    TO      STAT-POPMMEN .
      IF  NOT STAT-OK
          MOVE        "POPMMEN "          TO  ERR-FILE.
 8200-READL-POPMCMP.
      READ POPMCMP  WITH LOCK
                  .
      MOVE    STAT    TO      STAT-POPMCMP .
      IF  NOT STAT-OK
          MOVE        "POPMCMP "          TO  ERR-FILE.
 8200-READL-POPMCAR.
      READ POPMCAR  WITH LOCK
                  .
      MOVE    STAT    TO      STAT-POPMCAR .
      IF  NOT STAT-OK
          MOVE        "POPMCAR "          TO  ERR-FILE.
 8200-READL-POPMLOC.
      READ POPMLOC  WITH LOCK
                  .
      MOVE    STAT    TO      STAT-POPMLOC .
      IF  NOT STAT-OK
          MOVE        "POPMLOC "          TO  ERR-FILE.
 8200-READL-POPMPAY.
      READ POPMPAY  WITH LOCK
                  .
      MOVE    STAT    TO      STAT-POPMPAY .
      IF  NOT STAT-OK
          MOVE        "POPMPAY "          TO  ERR-FILE.
 8200-READL-POPMPRI.
      READ POPMPRI  WITH LOCK
                  .
      MOVE    STAT    TO      STAT-POPMPRI .
      IF  NOT STAT-OK
          MOVE        "POPMPRI "          TO  ERR-FILE.
*8200-READL-IMSMSRT.
*     READ IMSMSRT  WITH LOCK
*                 .
*     MOVE    STAT    TO      STAT-IMSMSRT .
*     IF  NOT STAT-OK
*         MOVE        "IMSMSRT "          TO  ERR-FILE.
 8300-WRITE-ORDVEND .
        WRITE ORDVEND-R             .
      MOVE    STAT    TO      STAT-ORDVEND .
      IF  NOT STAT-OK
          MOVE        "ORDVEND "          TO  ERR-FILE.
 8300-WRITE-POPMVDR .
        WRITE POPMVDR-R             .
      MOVE    STAT    TO      STAT-POPMVDR .
      IF  NOT STAT-OK
          MOVE        "POPMVDR "          TO  ERR-FILE.
 8300-REWRITE-POPMVDR .
      REWRITE POPMVDR-R      .
      MOVE    STAT    TO      STAT-POPMVDR .
      IF  NOT STAT-OK
          MOVE        "POPMVDR "          TO  ERR-FILE.
 8300-WRITE-POPMVDN .
        WRITE POPMVDN-R             .
      MOVE    STAT    TO      STAT-POPMVDN .
      IF  NOT STAT-OK
          MOVE        "POPMVDN "          TO  ERR-FILE.
 8300-REWRITE-POPMVDN .
      REWRITE POPMVDN-R      .
      MOVE    STAT    TO      STAT-POPMVDN .
      IF  NOT STAT-OK
          MOVE        "POPMVDN "          TO  ERR-FILE.
 8400-DELETE-POPMVDR .
      DELETE  POPMVDR   .
      MOVE    STAT    TO      STAT-POPMVDR .
      IF  NOT STAT-OK
          MOVE        "POPMVDR "          TO  ERR-FILE.
 8400-DELETE-POPMVDN .
      DELETE  POPMVDN   .
      MOVE    STAT    TO      STAT-POPMVDN .
      IF  NOT STAT-OK
          MOVE        "POPMVDN "          TO  ERR-FILE.
 8600-CLOSE-ALL.
      CLOSE                        ORDVEND .
      CLOSE                        POPMVDR .
      CLOSE                        POPMVDN .
      CLOSE                        POPMMEN .
      CLOSE                        POPMCMP .
      CLOSE                        POPMCAR .
      CLOSE                        POPMLOC .
      CLOSE                        POPMPAY .
      CLOSE                        POPMPRI .
      CLOSE                        INCMBNK .
*     CLOSE                        IMSMSRT .
 9000-INSERT-ORDVEND.
*     MOVE CA05 TO VENDER-NO OF ORDVEND-R
*     MOVE "1"  TO FORM-TYPE OF ORDVEND-R
*     PERFORM 8300-WRITE-ORDVEND
*     IF NOT STAT-OK
*        PERFORM    5092-ERR.
 9000-EXP .
*      COPY "PDA/LIB/PDATECK.FD".
       COPY "CMN/LIB/PDATECK".
